version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13  # Install Python 3.13
    commands:
      - echo "Installing dependencies..."
      - pip3 install --user pyyaml  # Install PyYAML for YAML parsing
      - pip3 install --user argparse  # Install argparse if needed for command-line arguments
  pre_build:
    commands:
      - echo "Setting up environment for YAML validation..."
      - python3 --version  # Verify Python version
  build:
    commands:
      - echo "Running YAML validator..."
      - python3 container-yaml-validator/validator.py --file image-recipes/*  # Run the validator script on all files in image-recipes directory
  post_build:
    commands:
      - echo "YAML validation completed on `date`"

artifacts:
  files:
    - '**/*'  # Keep all files as artifacts if needed for GitHub Actions reporting
  discard-paths: yes 