version: 0.2

env:
  variables:
    ECR_REGISTRY: ${ECR_REGISTRY}
    ECR_REPOSITORY: ${ECR_REPOSITORY}
    VERSION: ${VERSION}

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$VERSION-$COMMIT_HASH
      - echo "Version is set to $VERSION"
      - echo "Commit hash is $COMMIT_HASH"
      - echo "Image tag will be $IMAGE_TAG"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f container-codebuild-image/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      - echo Tagging image with latest...
      - docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - echo "Deleted existing 'latest' tag."
      - aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids imageTag=latest || true
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$ECR_REPOSITORY" "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files: imagedefinitions.json 