name: Build Docker Image

on:
  workflow_run:
    workflows: ["Deploy AWS Infrastructure"]
    types:
      - completed
  schedule:
    - cron: '0 0 * * 0'  # Run once every week on Sunday at midnight
  workflow_dispatch: # Allow manual trigger

permissions:
  actions: read    # Add permissions to read workflow runs
  contents: read   # Add permissions to read repository contents

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest
    env:
      # Single place to update the version
      BASE_IMAGE_VERSION: "1.0.1"
    steps:
      - name: Check Workflow Trigger
        if: github.event_name == 'workflow_run'
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "Infrastructure workflow did not succeed"
            exit 1
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-image-4codebuild
          env-vars-for-codebuild: |
            VERSION=${{ env.BASE_IMAGE_VERSION }}
