# aws-codebuild-docker-image/.github/workflows/deploy-infra.yml

name: Deploy AWS Infrastructure

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual trigger
    inputs:
      apply_changes:
        description: 'Apply Terraform changes after plan'
        required: false
        default: false
        type: boolean

      environment:
        description: 'Target environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production

      deployment_type:
        description: 'Type of deployment'
        required: false
        default: 'full'
        type: choice
        options:
          - full
          - incremental
          - rollback

      aws_region:
        description: 'AWS region for deployment'
        required: false
        default: 'us-east-1'
        type: string

      custom_tags:
        description: 'Custom tags to apply (comma-separated key=value pairs)'
        required: false
        default: 'project=aws-codebuild-docker-image,managed-by=terraform'
        type: string

      dry_run:
        description: 'Perform a dry run without making changes'
        required: false
        default: true
        type: boolean

      notification_email:
        description: 'Email address for deployment notifications'
        required: false
        default: 'devops@company.com'
        type: string

      timeout_minutes:
        description: 'Deployment timeout in minutes'
        required: false
        default: '30'
        type: number

      force_deploy:
        description: 'Force deployment even if there are warnings'
        required: false
        default: false
        type: boolean

jobs:
  DeployECRAndCodeBuild:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE_VERSION: "1.0.1"
      SCANNER_IMAGE_VERSION: "1.0.2"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Remove existing terraform state lock
        continue-on-error: true
        run: |
          aws dynamodb delete-item \
            --table-name docker-image-4codebuild-tfstate-lock \
            --key '{"LockID": {"S": "docker-image-4codebuild-tfstate/terraform.tfstate"}}' \
            --region us-east-1

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -upgrade

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        run: |
          cd terraform
          terraform plan -no-color \
            -var="aws_region=us-east-1" \
            -var="ecr_repo_name=docker-image-4codebuild-repo" \
            -var="docker_builder_project_name=docker-image-4codebuild" \
            -var="code_scanner_project_name=code-scanner-4codebuild" \
            -var="base_image_version=${{ env.BASE_IMAGE_VERSION }}" \
            -var="scanner_image_version=${{ env.SCANNER_IMAGE_VERSION }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' || (github.event_name == 'workflow_dispatch' && inputs.apply_changes == true)
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var="aws_region=us-east-1" \
            -var="ecr_repo_name=docker-image-4codebuild-repo" \
            -var="docker_builder_project_name=docker-image-4codebuild" \
            -var="code_scanner_project_name=code-scanner-4codebuild" \
            -var="base_image_version=${{ env.BASE_IMAGE_VERSION }}" \
            -var="scanner_image_version=${{ env.SCANNER_IMAGE_VERSION }}"
