name: PR Status Commenter

on:
  check_suite:
    types: [completed]
  check_run:
    types: [completed]

permissions:
  issues: write
  pull-requests: write
  checks: read
  contents: read

jobs:
  comment-on-pr:
    uses: chaunceyyann/cyan-actions/.github/workflows/reusable-pr-status-commenter.yml@dev
    with:
      required-checks: 'pre-commit,terraform-lint'
    secrets: inherit
