name: PR Status Commenter

on:
  check_suite:
    types: [completed]
  check_run:
    types: [completed]

permissions:
  issues: write
  pull-requests: write
  checks: read
  contents: read

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion != 'skipped'
    steps:
      - name: Comment on PR Status
        uses: chaunceyyann/cyan-actions/.github/actions/pr-status-commenter@dev
        with:
          required-checks: 'pre-commit,terraform-lint'
          prevent-duplicates: 'true'
          include-check-links: 'true'
          bot-name: 'PR Status Commenter App'
