name: TF Plan-Only CodePipeline Trigger

on:
  pull_request:
    types: [labeled]
    branches: [dev, master]

jobs:
  plan-only-codepipeline:
    if: contains(github.event.pull_request.labels.*.name, 'Attach Plan')
    uses: chaunceyyann/cyan-actions/.github/workflows/reusable-plan-only-pipeline.yml@v0.1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
