name: YAML Validator

on:
  push:
    paths:
      - 'image-recipes/**'  # Trigger on changes to YAML files in image-recipes directory

jobs:
  Validate-YAML:
    runs-on:
      - codebuild-codebuild-yaml-validator-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspecOverride=container-yaml-validator/buildspec.yml  # Optional override if needed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run YAML Validator
        run: |
          echo "Validating YAML files in image-recipes directory..."
          # The buildspec in CodeBuild will handle the validation
      - name: Upload Validation Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: validation-results
          path: '**/*'  # Upload any artifacts or logs from validation